# Generated by Django 3.2.3 on 2021-06-13 14:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('access_token', models.TextField(unique=True)),
                ('refresh_token', models.TextField(unique=True)),
                ('scope', models.TextField()),
                ('token_type', models.TextField()),
                ('expires_in', models.DateTimeField()),
            ],
            options={
                'db_table': 'credentials',
            },
        ),
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.TextField()),
                ('playlist_name', models.TextField()),
                ('playlist_url', models.TextField()),
                ('playlist_uri', models.TextField()),
                ('playlist_total_tracks', models.IntegerField(blank=True, null=True)),
                ('playlist_public', models.BooleanField(blank=True, null=True)),
                ('playlist_image', models.TextField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify_Auth.credentials')),
            ],
            options={
                'db_table': 'playlist_data',
            },
        ),
        migrations.CreateModel(
            name='TracksData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.TextField()),
                ('track_link', models.TextField()),
                ('album_name', models.TextField()),
                ('album_link', models.TextField()),
                ('album_image', models.TextField()),
                ('artist_name', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('artist_link', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spotify_Auth.playlistdata')),
            ],
            options={
                'db_table': 'tracks_data',
            },
        ),
    ]
