# Generated by Django 3.2.3 on 2021-05-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('username', models.AutoField(primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=300, unique=True)),
                ('refresh_token', models.CharField(max_length=300, unique=True)),
                ('scope', models.CharField(max_length=1000)),
                ('token_type', models.CharField(max_length=50)),
                ('expires_in', models.DateTimeField()),
            ],
            options={
                'db_table': 'Credentials',
            },
        ),
    ]
