# Generated by Django 3.2.3 on 2021-05-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify_Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
