# Generated by Django 3.2.3 on 2021-06-13 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify_Auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracksdata',
            old_name='playlist_id',
            new_name='playlist',
        ),
    ]
