# Generated by Django 3.2.3 on 2021-06-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify_Auth', '0004_alter_credentials_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='access_token',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='refresh_token',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='scope',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='token_type',
            field=models.TextField(),
        ),
    ]
