# Generated by Django 3.2.3 on 2021-06-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify_Auth', '0006_auto_20210613_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistdata',
            name='playlist_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
